name: healthbridge_bd
version: 0.1.0+1
publish_to: 'none'
description: HealthBridge BD mobile application

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
